name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildnpush:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Hub Login
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build the docker image
        run: docker build -t devopscp-app:latest .

      - name: Tag the image
        run: docker tag devopscp-app:latest moizzz407/app1:latest

      - name: Push the image
        run: docker push moizzz407/app1:latest
